name: testing_groud

on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  testing_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execure workflow
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.SEARCHTWEETS_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.SEARCHTWEETS_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.SEARCHTWEETS_CONSUMER_SECRET }}
          OBSEI_CONFIG_PATH: /tmp
          OBSEI_CONFIG_FILENAME: workflow.yaml
          WORKFLOW: ${{ secrets.WORKFLOW }}
        run: |
          echo "${WORKFLOW}" > "${OBSEI_CONFIG_PATH}/${OBSEI_CONFIG_FILENAME}"
          python workflow.py
